version: "3.8"
services:
  mongors1:
    container_name: mongors1
    image: mongo:4.4
    volumes:
      - mongorsdata1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    ports:
      - 37017:27017
    networks:
      - mongors-network
    links:
      - mongors2
      - mongors3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongors2:
    container_name: mongors2
    image: mongo:4.4
    volumes:
      - mongorsdata2:/data/db
    ports:
      - 37018:27017
    networks:
      - mongors-network
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongors3:
    container_name: mongors3
    image: mongo:4.4
    volumes:
      - mongorsdata3:/data/db
    ports:
      - 37019:27017
    networks:
      - mongors-network
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongors-express:
    container_name: mongors-express
    image: mongo-express
    ports:
      - 8802:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://mongors1:27017,mongors2:27017,mongors3:27017/?replicaSet=dbrs
    networks:
      - mongors-network
    restart: always

volumes:
  mongorsdata1:
    driver: local
  mongorsdata2:
    driver: local
  mongorsdata3:
    driver: local

networks:
  mongors-network:
    driver: bridge